# Site settings
author: M. Sumi
title: Software Engineering 
header-img: img/home-bg.png
email: msumi@mba2019.hbs.edu
copyright_name: M. Sumi
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  motoakisumi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
